[package]
name = "rk_kernel"
version = "0.1.0"
authors = ["Vegard Skui <me@vegardskui.com>"]
edition = "2018"
publish = false

[dependencies]
"lazy_static" = { version = "1.4.0", features = ["spin_no_std"] }
"rk_x86_64" = { path = "../libs/rk_x86_64" }
"spin" = "0.7.0"
