[package]
name = "uefi-rust"
version = "0.1.0"
authors = ["Vegard Skui <me@vegardskui.com>"]
edition = "2018"
publish = false

[dependencies]
"rk_uefi" = { path = "libs/rk_uefi" }
"rk_x86_64" = { path = "libs/rk_x86_64" }

[workspace]
