[package]
name = "uefi-rust"
version = "0.1.0"
authors = ["Vegard Skui <me@vegardskui.com>"]
edition = "2018"
publish = false

[dependencies]
"rlibc" = "1.0.0"
"rk_uefi" = { path = "libs/rk_uefi" }

[workspace]
